version: "2"

services:
  web:
    extends:
      file: ./docker-compose-common.yml
      service: drupal-php-apache-dev
    ports:
      - 8091:80
    depends_on:
      - mysql
      - redis
      - mail

#  php:
#    extends:
#      file: ./docker-compose-common.yml
#      service: drupal-php-dev

  varnish:
    extends:
      file: ./docker-compose-common.yml
      service: varnish
    depends_on:
      - web
    ports:
      - 8090:80


  mysql:
    extends:
      file: ./docker-compose-common.yml
      service: mysql
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./data/db:/var/lib/mysql


  redis:
    image: redis:3.2-alpine


  mail:
    image: djfarrelly/maildev
    ports:
      - 8095:80
